// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CountryViewer.DataAccess.DataContext;
using CountryViewer.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CountryViewer.DataAccess.DataContext.Configurations
{
    public partial class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> entity)
        {
            entity.Property(e => e.Code).IsFixedLength();

            entity.HasOne(d => d.Continent).WithMany(p => p.Countries).HasConstraintName("FK_Country_Continent");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Country> entity);
    }
}
