// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CountryViewer.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CountryViewer.DataAccess.DataContext
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<List<GetContinentWithCountryCountResult>> GetContinentWithCountryCountAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetCountriesByContinentResult>> GetCountriesByContinentAsync(string ContinentName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SearchCountryByNameResult>> SearchCountryByNameAsync(string NameSearchText, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
