// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CountryViewer.DataAccess.Models
{
    public partial class GetContinentWithCountryCountResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? CountryCount { get; set; }
    }
}
